import { test } from 'node:test';
import assert from 'node:assert/strict';
import { registerHooks } from 'node:module';
import { readFileSync } from 'node:fs';
registerHooks({resolve(specifier, context, nextResolve) {try{return nextResolve(specifier,context);}catch(error){if(specifier.startsWith('.')&&!/\.[a-z]+$/.test(specifier))return nextResolve(specifier+'.ts',context);throw error;}}});
const {aggregate,productCode,resolvePath,summarize,copyRows,toCsv,validateState,blankProduct}=await import('../lib/shipping.ts');
const {readFile,parseCsv,exportSummary}=await import('../lib/workbook.ts');
const {parseProducts,detectProductHeader}=await import('../lib/product-import.ts');
const ExcelJS=(await import('exceljs')).default;
const aliases=[{id:'root',name:'图库',path:'D:\\图库'},{id:'out',name:'目标',path:'E:\\发货'}];
const p={...blankProduct('001'),name:'挂历',mode:'模式A',category:'纸质类',subcategory:'挂历',note:'中'.repeat(60),paths:[{source:{kind:'alias',aliasId:'root',value:'挂历'},target:{kind:'alias',aliasId:'out',value:'纸质'}},{source:{kind:'manual',aliasId:'',value:'F:\\另一处'},target:{kind:'manual',aliasId:'',value:'G:\\发货'}}]};
const state={products:[p],aliases,batches:[]};
test('aggregate exact SKU, keep variants separate and leading zeros',()=>{const result=aggregate([['SKU','数量'],['001-A','2'],['001-A','3'],['001-B',4],[],['002',1]],0,1,0);assert.deepEqual(result.rows,[{sku:'001-A',quantity:5},{sku:'001-B',quantity:4},{sku:'002',quantity:1}]);assert.equal(result.sourceRows,4);assert.equal(result.issues.length,0);assert.equal(productCode('001-A-B'),'001');assert.equal(productCode('002'),'002');});
test('bad rows block import and report original lines',()=>{const result=aggregate([['SKU','数量'],['',1],['A',0],['B',-1],['C','2.5'],['D',''],['E','=1+2']],0,1,0);assert.equal(result.issues.length,6);assert.match(result.issues[0],/第 2 行/);assert.throws(()=>aggregate([],0,0,0));});
test('path resolution and paired expansion do not inflate mode totals',()=>{assert.equal(resolvePath(p.paths[0].source,aliases),'D:\\图库\\挂历');assert.equal(resolvePath({kind:'alias',aliasId:'root',value:''},aliases),'D:\\图库');const rows=[{sku:'001-A',quantity:5}];const result=copyRows(rows,state);assert.deepEqual(result,[['D:\\图库\\挂历','001-A','E:\\发货\\纸质',5],['F:\\另一处','001-A','G:\\发货',5]]);assert.deepEqual(summarize(rows,[p]).modes,[['模式A',5]]);assert.equal(summarize([...rows,{sku:'002-A',quantity:2}],[p]).unmatched,2);assert.throws(()=>copyRows([{sku:'002-A',quantity:2}],state),/建立产品信息/);});
test('CSV headers, BOM, quotes, commas, newline and formula protection',()=>{const csv=toCsv([['源文件夹','文件名','目标文件夹','复制数量'],['D:\\a,b','001-A','E:\\"目标"',5]]);assert.equal(csv.charCodeAt(0),0xFEFF);assert.deepEqual(parseCsv(csv)[1],['D:\\a,b','001-A','E:\\"目标"','5']);assert.deepEqual(parseCsv('"a\nb",c\r\n'),[['a\nb','c']]);assert.throws(()=>toCsv([['=HYPERLINK("x")']]),/执行/);assert.throws(()=>parseCsv('"not closed'),/未闭合/);});
test('server validation rejects duplicate codes, notes over 60, missing aliases and incomplete paths',()=>{validateState(state);assert.throws(()=>validateState({...state,products:[p,{...p,id:'second'}]}),/重复/);assert.throws(()=>validateState({...state,products:[{...p,note:'中'.repeat(61)}]}),/备注/);assert.throws(()=>validateState({...state,aliases:[]}),/不存在/);assert.throws(()=>validateState({...state,products:[{...p,paths:[]}]}),/路径/);});
test('provided workbook range anomaly: 370 details, 312 SKUs, 433 pieces',async()=>{const filePath=process.env.SAMPLE_WORKBOOK;if(!filePath)return;const bytes=readFileSync(filePath);const sheets=await readFile(new File([bytes],'0828第二批店小秘.xlsx'));const rows=sheets[0].rows;assert.equal(rows[0][9],'SKU货号');assert.equal(rows[0][14],'发货数');const result=aggregate(rows,9,14,0);assert.equal(result.sourceRows,370);assert.equal(result.rows.length,312);assert.equal(result.rows.reduce((n,r)=>n+r.quantity,0),433);assert.deepEqual(result.issues,[]);});
test('summary workbook has three exact columns and text SKUs',async()=>{let saved;const oldCreate=URL.createObjectURL;URL.createObjectURL=blob=>{saved=blob;return 'blob:test';};globalThis.document={createElement:()=>({click(){}})};try{await exportSummary({id:'test',name:'test.xlsx',createdAt:'2026-08-28',sourceRows:2,rows:[{sku:'001-A',quantity:5},{sku:'002-A',quantity:2}]},[p]);const book=new ExcelJS.Workbook();await book.xlsx.load(await saved.arrayBuffer());assert.deepEqual(book.worksheets[0].getRow(1).values.slice(1),['SKU货号','数量','产品货号']);assert.equal(book.worksheets[0].getCell('A2').value,'001-A');assert.equal(book.worksheets[0].getCell('B2').value,5);assert.equal(book.worksheets[0].getCell('C2').value,'001');assert.match(book.worksheets[0].getCell('C3').value,/请建立产品信息/);}finally{URL.createObjectURL=oldCreate;delete globalThis.document;}});


test('bulk product import groups repeated product rows into path pairs',()=>{const headers=['产品图片','产品货号','产品模式','产品名称','一级分类','二级分类','源路径填写方式','源路径或剩余路径','源通用名称','目标路径填写方式','目标路径或剩余路径','目标通用名称','备注'];const rows=[headers,['https://example.com/a.jpg','A001','模式A','测试挂历','纸质类','挂历','通用','挂历','图库','完整','E:\\发货','','注意'],['https://example.com/a.jpg','A001','模式A','测试挂历','纸质类','挂历','完整','F:\\备用','','通用','纸质','发货目录','注意']];const aliases=[{id:'source','name':'图库','path':'D:\\图库'},{id:'target','name':'发货目录','path':'G:\\发货'}];assert.equal(detectProductHeader(rows),0);const result=parseProducts(rows,0,[],aliases,()=> 'id-a');assert.deepEqual(result.issues,[]);assert.equal(result.newCount,1);assert.equal(result.products[0].paths.length,2);assert.equal(result.products[0].paths[0].source.aliasId,'source');assert.equal(result.products[0].paths[1].target.aliasId,'target');});
test('bulk product import blocks bad rows without partial success',()=>{const headers=['产品图片','产品货号','产品模式','产品名称','一级分类','二级分类','源路径填写方式','源路径或剩余路径','源通用名称','目标路径填写方式','目标路径或剩余路径','目标通用名称','备注'];const base=['','A001','模式A','名称一','纸质类','挂历','通用','','不存在','完整','E:\\发货','',''];const second=[...base];second[3]='名称二';const bad=parseProducts([headers,base,second],0,[],[],()=> 'id');assert(bad.issues.some(x=>x.includes('找不到通用路径')));assert(bad.issues.some(x=>x.includes('资料与第')));assert(parseProducts([headers.slice(0,-1)],0,[],[]).issues.some(x=>x.includes('缺少表头')));});
test('CSV payload is plain UTF-8 text, not XLS or XLSX bytes',()=>{const csv=toCsv([['源文件夹','文件名','目标文件夹','复制数量'],['D:\\a','A001-x','E:\\b',2]]);const bytes=new TextEncoder().encode(csv);assert.deepEqual(Array.from(bytes.slice(0,3)),[0xef,0xbb,0xbf]);assert.notDeepEqual(Array.from(bytes.slice(0,4)),[0xd0,0xcf,0x11,0xe0]);assert.notDeepEqual(Array.from(bytes.slice(0,2)),[0x50,0x4b]);assert.match(new TextDecoder().decode(bytes),/源文件夹/);});
