'use client';
import { useState } from 'react';
import { ImageIcon, Pencil, Plus, Trash2, Upload, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import type { AccessoryDefinition, Product } from '@/lib/shipping';

type Draft={id:string;name:string;imageKey:string};
const emptyDraft=():Draft=>({id:crypto.randomUUID(),name:'',imageKey:''});

export default function AccessoryCatalog({items,products,busy,onSave}:{items:AccessoryDefinition[];products:Product[];busy:boolean;onSave:(items:AccessoryDefinition[])=>Promise<void>}){
  const [draft,setDraft]=useState<Draft|null>(null),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[error,setError]=useState(''),[uploading,setUploading]=useState(false);
  const usage=(id:string)=>products.filter(product=>(product.accessories??[]).some(item=>item.accessoryId===id)).length;
  function choose(next?:File){if(!next)return;if(!['image/jpeg','image/png','image/webp'].includes(next.type)){setError('配件图片仅支持 JPG、PNG 或 WebP');return;}if(next.size>5_000_000){setError('配件图片须小于5 MB');return;}setError('');setFile(next);const reader=new FileReader();reader.onload=()=>setPreview(String(reader.result||''));reader.readAsDataURL(next);}
  async function uploadImage(){if(!file)throw new Error('请从本地上传配件图片');const form=new FormData();form.set('file',file);const response=await fetch('/api/accessories/upload',{method:'POST',body:form});const data=await response.json() as {imageKey?:string;error?:string};if(!response.ok||!data.imageKey)throw new Error(data.error||'配件图片上传失败');return data.imageKey;}
  async function submit(){if(!draft)return;setError('');setUploading(true);try{const name=draft.name.trim();if(!name)throw new Error('请填写配件名称');if(items.some(item=>item.id!==draft.id&&item.name.trim()===name))throw new Error('配件名称不能重复');const imageKey=file?await uploadImage():draft.imageKey;const next={id:draft.id,name,imageKey};await onSave(items.some(item=>item.id===draft.id)?items.map(item=>item.id===draft.id?next:item):[...items,next]);setDraft(null);setFile(null);setPreview('');}catch(e){setError(e instanceof Error?e.message:'保存配件失败');}finally{setUploading(false);}}
  function edit(item?:AccessoryDefinition){setDraft(item?{...item}:emptyDraft());setFile(null);setPreview('');setError('');}
  return <><div className="heading"><div><p className="eyebrow">ACCESSORY LIBRARY</p><h1>配件资料</h1><p>配件名称必须填写，图片可以选择上传；商品资料中可直接选择。</p></div><Button disabled={busy||uploading} onClick={()=>edit()}><Plus/>新增配件</Button></div>{draft&&<div className="panel accessory-form"><div className="panelhead"><h2>{items.some(item=>item.id===draft.id)?'编辑配件':'新增配件'}</h2><Button variant="ghost" size="icon" disabled={uploading} onClick={()=>setDraft(null)}><X/></Button></div><div className="accessory-form-body"><div className="accessory-preview">{(preview||draft.imageKey)?<img src={preview||`/api/accessories/${draft.imageKey}`} alt={draft.name||'配件预览'}/>:<ImageIcon size={28}/>}<label><Upload size={15}/>{draft.imageKey||file?'更换图片':'上传图片'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>choose(e.target.files?.[0])}/></label></div><label>配件名称 <em>*</em><Input required maxLength={100} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="例如 挂钩"/></label></div>{error&&<div className="alert error">{error}</div>}<div className="dialogactions"><Button variant="outline" disabled={uploading} onClick={()=>setDraft(null)}>取消</Button><Button disabled={busy||uploading} onClick={()=>void submit()}>{uploading?'正在上传图片…':'保存配件'}</Button></div></div>}<div className="panel">{items.length?<div className="accessory-grid">{items.map(item=><article key={item.id}>{item.imageKey?<img src={`/api/accessories/${item.imageKey}`} alt={item.name}/>:<div className="accessory-card-placeholder"><ImageIcon size={24}/></div>}<div><h3>{item.name}</h3><p>{usage(item.id)} 件商品正在使用</p></div><div className="actions"><Button variant="ghost" size="icon" aria-label={`编辑${item.name}`} disabled={busy||uploading} onClick={()=>edit(item)}><Pencil size={15}/></Button><Button variant="ghost" size="icon" aria-label={`删除${item.name}`} disabled={busy||uploading||usage(item.id)>0} onClick={()=>{if(confirm(`删除配件“${item.name}”？`))void onSave(items.filter(value=>value.id!==item.id));}}><Trash2 size={15}/></Button></div></article>)}</div>:<div className="empty"><ImageIcon/><p>还没有配件资料</p><small>新增配件后，商品资料中的配件名称会出现在下拉框里。</small></div>}</div></>;
}
