'use client';
import {useEffect,useState} from 'react';
import {Package,Plus,RefreshCw,LogOut,Users} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export type AuthUser={id:string;username:string;isAdmin:boolean};
export function Login({onLogin}:{onLogin:(user:AuthUser)=>void}){const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <main className="loginpage"><form className="loginbox" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const data=await r.json() as any;if(!r.ok)throw new Error(data.error||'登录失败');onLogin(data.user);}catch(e){setError(e instanceof Error?e.message:'登录失败');}finally{setBusy(false);}}}><div className="loginbrand"><Package/><h1>发货工作台</h1><p>请使用管理员分配的账号登录</p></div><label>账号<Input required autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} /></label><label>密码<Input required type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="alert error">{error}</div>}<Button type="submit" size="lg" disabled={busy}>{busy?'正在登录…':'登录'}</Button></form></main>}
type ManagedUser={id:string;username:string;is_admin:number;active:number;created_at:string};
export function AccountManager({open,onClose}:{open:boolean;onClose:()=>void}){const [users,setUsers]=useState<ManagedUser[]>([]),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function load(){const r=await fetch('/api/auth/users');const d=await r.json() as any;if(!r.ok)throw new Error(d.error);setUsers(d.users);}useEffect(()=>{if(open)void load().catch(e=>setError(e.message));},[open]);async function act(fn:()=>Promise<Response>){setBusy(true);setError('');try{const r=await fn(),d=await r.json() as any;if(!r.ok)throw new Error(d.error||'操作失败');await load();}catch(e){setError(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}}return <Dialog open={open} onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent className="accountdialog"><DialogTitle>登录账号管理</DialogTitle><DialogDescription>创建可登录此工作台的账号，或重置密码、停用访问权限。</DialogDescription><form className="accountcreate" onSubmit={e=>{e.preventDefault();void act(()=>fetch('/api/auth/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})})).then(()=>{setUsername('');setPassword('');});}}><Input required minLength={3} maxLength={32} value={username} onChange={e=>setUsername(e.target.value)} placeholder="新账号（字母、数字、下划线）"/><Input required type="password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} placeholder="初始密码（至少6位）"/><Button type="submit" disabled={busy}><Plus/>创建账号</Button></form>{error&&<div className="alert error">{error}</div>}<div className="accountlist">{users.map(u=><div key={u.id}><span><b>{u.username}</b><small>{u.is_admin?'管理员':u.active?'正常':'已停用'}</small></span><div className="actions">{<Button variant="outline" disabled={busy} onClick={()=>{const next=prompt(`为 ${u.username} 设置新密码（至少6位）`);if(next)void act(()=>fetch('/api/auth/users',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:u.id,password:next})}));}}><RefreshCw/>重置密码</Button>}{!u.is_admin&&<Button variant="ghost" disabled={busy} onClick={()=>void act(()=>fetch('/api/auth/users',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:u.id,active:!u.active})}))}>{u.active?'停用':'启用'}</Button>}</div></div>)}</div></DialogContent></Dialog>}
export function UserActions({user,onAccounts,onLogout}:{user:AuthUser;onAccounts:()=>void;onLogout:()=>void}){return <div className="actions"><span className="pill">{user.username}</span>{user.isAdmin&&<Button variant="ghost" onClick={onAccounts}><Users/>账号管理</Button>}<Button variant="ghost" onClick={onLogout}><LogOut/>退出</Button></div>}




