'use client';
import { useState } from 'react';
import { Plus, Trash2, ArrowRight, ImageIcon } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { blankPath, blankSkuRule, resolvePath, transformSku, type Product, type Alias, type PathValue, type Accessory, type AccessoryDefinition } from '@/lib/shipping';

export function ProductImage({url}: {url:string}){
  const [failed,setFailed]=useState(false);
  return url&&!failed?<img className="productimage" src={url} alt="产品图片" loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>:<div className="productimage placeholder"><ImageIcon size={20}/><small>{failed?'链接失效':'暂无图片'}</small></div>;
}
function PathInput({label,value,aliases,onChange}:{label:string;value:PathValue;aliases:Alias[];onChange:(v:PathValue)=>void}){
  let resolved='';try{resolved=resolvePath(value,aliases);}catch{resolved='请选择通用路径';}
  return <div className="pathinput"><label>{label}<select aria-label={`${label}填写方式`} value={value.kind} onChange={e=>onChange({...value,kind:e.target.value as PathValue['kind']})}><option value="manual">完整手写</option><option value="alias">通用前缀</option></select></label>{value.kind==='alias'&&<select aria-label={`${label}通用前缀`} value={value.aliasId} onChange={e=>onChange({...value,aliasId:e.target.value})}><option value="">选择通用路径</option>{aliases.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>}<Input aria-label={label} value={value.value} onChange={e=>onChange({...value,value:e.target.value})} placeholder={value.kind==='manual'?'例如 D:\\产品资料\\挂历':'填写剩余路径，可留空'}/><div className="resolved" title={resolved}>{resolved||'完整路径将在这里显示'}</div></div>;
}
const blankAccessory=():Accessory=>({id:crypto.randomUUID(),accessoryId:'',quantity:1});

export default function ProductEditor({initial,products,aliases,accessoryCatalog,categoryOptions,modeOptions,busy,onSave,onClose}:{initial:Product;products:Product[];aliases:Alias[];accessoryCatalog:AccessoryDefinition[];categoryOptions:string[];modeOptions:string[];busy:boolean;onSave:(p:Product)=>Promise<boolean>;onClose:()=>void}){
  const [draft,setDraft]=useState<Product>(()=>({...structuredClone(initial),layoutType:initial.layoutType||'',writeAccessories:Boolean(initial.writeAccessories),accessories:initial.accessories??[]}));
  const [error,setError]=useState(''),[previewSku,setPreviewSku]=useState(initial.code?`${initial.code}-1000-1PC`:'');
  const change=(key:keyof Product,value:string)=>setDraft(p=>({...p,[key]:value})),editing=products.some(p=>p.id===initial.id),accessories=draft.accessories??[];
  async function submit(){setError('');try{if(!draft.layoutType)throw new Error('请选择设计排版或非设计排版');if(draft.writeAccessories&&(accessories.length<1||accessories.length>15))throw new Error('选择写入配件时，须添加1至15个配件');if(draft.writeAccessories&&!accessoryCatalog.length)throw new Error('请先到“配件”页面建立配件');const selected=new Set<string>();for(const item of draft.writeAccessories?accessories:[]){if(!item.accessoryId)throw new Error('请选择配件名称');if(selected.has(item.accessoryId))throw new Error('同一商品不能重复选择同一个配件');selected.add(item.accessoryId);if(!Number.isSafeInteger(item.quantity)||item.quantity<1||item.quantity>99999)throw new Error('配件数量须为1至99999的整数');}await onSave({...draft,code:draft.code.trim(),name:draft.name.trim(),mode:draft.mode.trim(),category:draft.category.trim(),subcategory:draft.subcategory.trim(),image:draft.image.trim(),writeAccessories:Boolean(draft.writeAccessories),accessories:draft.writeAccessories?accessories:[]});}catch(e){setError(e instanceof Error?e.message:'保存失败');}}
  return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="productdialog" showCloseButton={!busy}><DialogTitle>{editing?'编辑商品资料':'建立商品资料'}</DialogTitle><DialogDescription>产品货号用于匹配 SKU；配件请先在“配件”页面建立，再在商品中选择。</DialogDescription><form onSubmit={e=>{e.preventDefault();void submit();}}><div className="formgrid"><label>产品货号 <em>*</em><Input required maxLength={150} value={draft.code} onChange={e=>change('code',e.target.value)} placeholder="例如 A001"/><small>SKU 第一个 - 前面的内容</small></label><label>产品模式 <em>*</em><select required value={draft.mode} onChange={e=>change('mode',e.target.value)}><option value="">请选择产品模式</option>{modeOptions.map(m=><option key={m} value={m}>{m}</option>)}</select></label><label className="full">产品名称（选填）<Input maxLength={200} value={draft.name} onChange={e=>change('name',e.target.value)} placeholder="填写产品名称"/></label><label>排版分类 <em>*</em><select required value={draft.layoutType||''} onChange={e=>change('layoutType',e.target.value)}><option value="">请选择</option><option value="设计排版">设计排版</option><option value="非设计排版">非设计排版</option></select></label><label>产品分类 <em>*</em><select required value={draft.category} onChange={e=>change('category',e.target.value)}><option value="">请选择产品分类</option>{categoryOptions.map(c=><option key={c} value={c}>{c}</option>)}</select></label><label>是否需要打印 <em>*</em><select value={draft.printRequired?'是':'否'} onChange={e=>setDraft(p=>({...p,printRequired:e.target.value==='是'}))}><option value="否">否</option><option value="是">是</option></select></label><label>是否写入配件 <em>*</em><select value={draft.writeAccessories?'是':'否'} onChange={e=>{const yes=e.target.value==='是';setDraft(p=>({...p,writeAccessories:yes,accessories:yes?(p.accessories?.length?p.accessories:[blankAccessory()]):[]}));}}><option value="否">否</option><option value="是">是</option></select><small>默认否；选择是后须选择配件</small></label><label className="full">网络图片链接<Input type="url" value={draft.image} onChange={e=>change('image',e.target.value)} placeholder="https://…"/></label>{draft.image&&<ProductImage key={draft.image} url={draft.image}/>}</div>
  {draft.writeAccessories&&<section className="accessory-section"><div className="sectiontitle"><div><h3>商品配件</h3><small>名称来自“配件”页面，最多选择 15 个</small></div><Button type="button" variant="outline" disabled={accessories.length>=15||!accessoryCatalog.length} onClick={()=>setDraft(p=>({...p,accessories:[...(p.accessories??[]),blankAccessory()]}))}><Plus/>添加配件</Button></div>{!accessoryCatalog.length&&<div className="alert warning">请先到“配件”页面建立配件名称。</div>}{accessories.map((item,index)=>{const definition=accessoryCatalog.find(a=>a.id===item.accessoryId);return <div className="accessory-row compact" key={item.id}>{definition?.imageKey?<img src={`/api/accessories/${definition.imageKey}`} alt={definition.name}/>:<div className="accessory-thumb"><ImageIcon size={18}/></div>}<label>配件名称<select required value={item.accessoryId} onChange={e=>setDraft(p=>({...p,accessories:(p.accessories??[]).map(a=>a.id===item.id?{...a,accessoryId:e.target.value}:a)}))}><option value="">请选择配件</option>{accessoryCatalog.map(option=><option key={option.id} value={option.id} disabled={accessories.some(a=>a.id!==item.id&&a.accessoryId===option.id)}>{option.name}</option>)}</select></label><label>数量<Input required type="number" min={1} max={99999} step={1} value={item.quantity} onChange={e=>setDraft(p=>({...p,accessories:(p.accessories??[]).map(a=>a.id===item.id?{...a,quantity:Number(e.target.value)}:a)}))}/></label><Button type="button" variant="ghost" size="icon" aria-label={`删除配件${index+1}`} onClick={()=>setDraft(p=>({...p,accessories:(p.accessories??[]).filter(a=>a.id!==item.id)}))}><Trash2 size={15}/></Button></div>})}</section>}
  <div className="alert success">所有商品的文件复制路径均为选填；不填写时不写入 CSV，填写后按“是否打印”导出。</div><div className="sectiontitle"><div><h3>文件复制路径</h3><Input className="sku-preview-input" aria-label="测试SKU" value={previewSku} onChange={e=>setPreviewSku(e.target.value)} placeholder="输入实际 SKU 预览文件名"/></div><Button type="button" variant="outline" disabled={draft.paths.length>=50} onClick={()=>setDraft(p=>({...p,paths:[...p.paths,{source:blankPath(),target:blankPath(),skuRule:blankSkuRule()}]}))}><Plus/>添加一组</Button></div>{draft.paths.map((pair,index)=>{const rule=pair.skuRule??blankSkuRule();let result=previewSku;try{result=transformSku(previewSku,rule);}catch{result='删除段数过多';}return <div className="pathpair" key={index}><div className="pairlabel">路径 {String(index+1).padStart(2,'0')}<Button type="button" variant="ghost" size="icon-sm" aria-label={`删除路径${index+1}`} onClick={()=>setDraft(p=>({...p,paths:p.paths.filter((_,i)=>i!==index)}))}><Trash2 size={14}/></Button></div><div className="pairfields"><PathInput label="源文件夹" value={pair.source} aliases={aliases} onChange={v=>setDraft(p=>({...p,paths:p.paths.map((item,i)=>i===index?{...item,source:v}:item)}))}/><ArrowRight className="patharrow"/><PathInput label="目标文件夹" value={pair.target} aliases={aliases} onChange={v=>setDraft(p=>({...p,paths:p.paths.map((item,i)=>i===index?{...item,target:v}:item)}))}/></div><div className="sku-rule"><label className="rule-toggle"><input type="checkbox" checked={rule.enabled} onChange={e=>setDraft(p=>({...p,paths:p.paths.map((item,i)=>i===index?{...item,skuRule:{...rule,enabled:e.target.checked}}:item)}))}/>处理此路径的 SKU 文件名</label>{rule.enabled&&<div className="rule-fields"><label>删除末尾分段<Input type="number" min={0} max={20} value={rule.dropSegments} onChange={e=>setDraft(p=>({...p,paths:p.paths.map((item,i)=>i===index?{...item,skuRule:{...rule,dropSegments:Number(e.target.value)}}:item)}))}/><small>按 “-” 分段；删除 1 段会移除 -1PC</small></label><label>追加文字<Input maxLength={100} value={rule.append} onChange={e=>setDraft(p=>({...p,paths:p.paths.map((item,i)=>i===index?{...item,skuRule:{...rule,append:e.target.value}}:item)}))} placeholder="例如 -F"/></label><div className="rule-preview"><span>CSV 文件名预览</span><b>{result||'请输入测试 SKU'}</b></div></div>}</div></div>})}<label className="notelabel">备注<span>{Array.from(draft.note).length} / 60</span><Textarea value={draft.note} onChange={e=>change('note',Array.from(e.target.value).slice(0,60).join(''))} placeholder="生产、包装或发货时需要留意的事项"/></label>{error&&<div className="alert error" role="alert">{error}</div>}<div className="dialogactions"><Button type="button" variant="outline" disabled={busy} onClick={onClose}>取消</Button><Button type="submit" disabled={busy}>{busy?'正在保存…':'保存商品资料'}</Button></div></form></DialogContent></Dialog>;
}
